---
abstract: 'report prerequisite versions'
author:
  - 'Sven Kirmess <sven.kirmess@kzone.ch>'
build_requires:
  Test::More: '0.88'
  lib: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 1
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-ReportPrereqs
no_index:
  directory:
    - corpus
    - t
    - xt
provides:
  App::ReportPrereqs:
    file: bin/report-prereqs
    version: '0.006'
requires:
  ExtUtils::MakeMaker: '0'
  File::Basename: '0'
  Getopt::Long: '0'
  HTTP::Tiny: '0.014'
  List::Util: '0'
  Module::CPANfile: '0'
  Module::Path: '0'
  perl: '5.006'
  strict: '0'
  version: '0.77'
  warnings: '0'
resources:
  bugtracker: https://github.com/skirmess/App-ReportPrereqs/issues
  homepage: https://github.com/skirmess/App-ReportPrereqs
  repository: https://github.com/skirmess/App-ReportPrereqs.git
version: '0.006'
x_contributors:
  - 'Stephan Sachse <ste.sachse@gmail.com>'
x_spdx_expression: BSD-2-Clause-FreeBSD
