---
abstract: 'Report prerequisite versions'
author:
  - 'Sven Kirmess <sven.kirmess@kzone.ch>'
build_requires:
  Capture::Tiny: '0'
  Cwd: '0'
  FindBin: '0'
  Test::More: '0.88'
  lib: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-ReportPrereqs
no_index:
  directory:
    - corpus
    - t
    - xt
provides:
  App::ReportPrereqs:
    file: bin/report-prereqs
    version: '0.001'
requires:
  ExtUtils::MakeMaker: '0'
  File::Basename: '0'
  Getopt::Long: '0'
  List::Util: '0'
  Module::CPANfile: '0'
  Module::Path: '0'
  perl: '5.006'
  strict: '0'
  version: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/skirmess/App-ReportPrereqs/issues
  homepage: https://github.com/skirmess/App-ReportPrereqs
  repository: https://github.com/skirmess/App-ReportPrereqs.git
version: '0.001'
x_generated_by_perl: v5.24.0
x_serialization_backend: 'YAML::Tiny version 1.70'
